### ISSUE TITLE
New Section for Tutorial Notebooks

### ISSUE THREAD

**Issue by SauravMaheshkar** [kjw0612/awesome-rnn#38]
Hey,

There is no given section for **end-to-end** machine learning tutorials using Recurrent Neural Networks like Text Classification and Question Answering. There are papers, but **no links for Implementations**.

I would like to add such tutorial notebooks.

**Comment by andreaschandra** [comment]
@SauravMaheshkar have you pull request?

**Comment by SauravMaheshkar** [comment]
Yes, in #39 I've added tutorials for Fake News Classification using Tensorflow.
